#######################################
## Development-only properties
#######################################
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
app.seed.password=${APP_SEED_PASSWORD}
